image: maven:latest

stages:
  - linting
  - test
  - build

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

linting:
  stage: linting
  script:
    - mvn -T 1C spotless:check

test:
  stage: test
  script:
    - mvn -T 1C test -Dspotless.check.skip=true

build:
  stage: build
  script:
    - mvn -T 1C package -Dmaven.test.skip -DskipTests -Dspotless.check.skip=true
