image: maven:latest

stages:
  - linting
  - test
  - build

linting:
  stage: linting
  script:
    - mvn spotless:check
test:
  stage: test
  script:
    - mvn clean test

build:
  stage: build
  script:
    mvn clean package