image: maven:latest

stages:
  - linting
  - test
  - build

linting:
  stage: linting
  script:
    - mvn spotless:check
test:
  stage: test
  script:
    - mvn clean test -Dspotless.check.skip=true

build:
  stage: build
  script:
    mvn clean package -DskipTests -Dspotless.check.skip=true