image: maven:latest

stages:
  - linting
  - test
  - build

linting:
  stage: linting
  script:
    - mvn spotless:check

test:
  stage: test
  script:
    - mvn test -Dspotless.check.skip=true

build:
  stage: build
  script:
    - mvn package -Dmaven.test.skip -DskipTests -Dspotless.check.skip=true
