# Cache maven docker image in GitLab
image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/maven:latest

stages:
  - linting
  - test
  - build

linting:
  stage: linting
  # No needs - Can run in parallel with other stages
  needs: []
  script:
    # One thread per core
    - mvn spotless:check

test:
  stage: test
  needs: []
  script:
    - mvn clean test -Dspotless.check.skip=true

build:
  stage: build
  needs: []
  script:
    - mvn clean package -Dmaven.test.skip -Dspotless.check.skip=true
