# Cache maven docker image in GitLab
image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/maven:latest

stages:
  - linting
  - test
  - build

# Cache Maven dependencies
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

linting:
  stage: linting
  # No needs - Can run in parallel with other stages
  needs: []
  script:
    # One thread per core
    - mvn -T 1C spotless:check

test:
  stage: test
  needs: []
  script:
    - mvn test -Dspotless.check.skip=true -Dparallel=all -DperCoreThreadCount=true

build:
  stage: build
  needs: []
  script:
    - mvn -T 1C package -Dmaven.test.skip -Dspotless.check.skip=true
