image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/maven:latest

stages:
  - linting
  - test
  - build

cache:
  key: target-cache
  paths:
    - target

linting:
  stage: linting
  script:
    - mvn spotless:check

test:
  stage: test
  script:
    - mvn test -Dspotless.check.skip=true

build:
  stage: build
  script:
    - mvn package -Dmaven.test.skip -DskipTests -Dspotless.check.skip=true
