# Define stages
stages:
  - build
  - linting
  - test

default:
  # Cache maven docker image in GitLab
  image: maven:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .m2/

# Define variables
variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_BUILD_CLI_OPTS: >-
    -DskipTests -Dspotless.check.skip=true
  MAVEN_TEST_CLI_OPTS: >-
    -Dspotless.check.skip=true
    

build:
  stage: build
  script:
    - mvn $MAVEN_BUILD_CLI_OPTS package

test:
  stage: test
  needs: ["build"]
  script:
    - mvn $MAVEN_TEST_CLI_OPTS test

linting:
  stage: test
  needs: ["build"]
  script:
    - mvn spotless:check
