image: maven:latest

stages:
  # - linting
  - test
  - build

#linting: todo: add mvn dependency (e.g spotless)

test:
  stage: test
  script:
    - mvn clean test

build:
  stage: build
  script:
    mvn clean package