# Define stages
stages:
  - build
  - linting
  - test

default:
  # Cache maven docker image in GitLab
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/maven:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .m2/

# Define variables
variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_BUILD_CLI_OPTS: >-
    -DskipTests -Dspotless.check.skip=true
  MAVEN_TEST_CLI_OPTS: >-
    -Dspotless.check.skip=true

build:
  stage: build
  script:
    - mvn $MAVEN_BUILD_CLI_OPTS package

test:
  needs: ["build"]
  stage: test
  script:
    - |
      set +o errexit
      END=1
      for i in $(seq 1 $END); do
          echo "Execution no. $i"
          mvn -T 1C surefire:test && exit 0
      done
      exit 1

linting:
  needs: ["build"]
  stage: linting
  script:
    - |
      set +o errexit
      END=1
      for i in $(seq 1 $END); do
          echo "Execution no. $i"
          mvn spotless:check && exit 0
      done
      exit 1
