# Define stages
stages:
  - build
  - linting
  - test
  - deploy

default:
  # Cache maven docker image in GitLab
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/maven:latest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .m2/

# Define variables
variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  MAVEN_BUILD_CLI_OPTS: >-
    -DskipTests -Dspotless.check.skip=true
  MAVEN_TEST_CLI_OPTS: >-
    -Dspotless.check.skip=true
    

build:
  stage: build
  script:
    - mvn $MAVEN_BUILD_CLI_OPTS package

test:
  stage: test
  script:
    - mvn $MAVEN_TEST_CLI_OPTS test
  retry: 1

linting:
  stage: linting
  script:
    - mvn spotless:check

deploy:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa # Required permission by ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - apt-get update
    - apt-get install --assume-yes rsync
    - apt-get install --assume-yes openssh-client

    # - rsync --archive --delete --exclude='.git' --exclude='.env' . student@129.241.98.22:idatt2106_2024_02_backend
    - scp idatt2106_2024_02_backend student@129.241.98.22:/
    - ssh student@idatt2105-22 echo "Sparesti123!" | sudo -S systemctl restart sparesti_backed.service
  only:
    - dev
    - main
    - feat/cd