services:
  mysql:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'db', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      # Run health check <start_interval> seconds after container start.
      start_interval: 9s
      # Proceeding checks are spaced by <interval> seconds
      interval: 5s
      # Fail check if it takes longer than 5
      timeout: 5s
      # Max 50 tries
      retries: 50
    env_file:
      - .env
  app:
    container_name: sparesti-backend
    depends_on:
      mysql:
          condition: service_healthy
    build: .
    # Make app container to wait on mysql container to spin up by restarting it
    restart: always
    environment:
      MYSQL_HOST: db
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '8080:8080'
    env_file:
      - .env